name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

# TODO: set -vxeuo pipefail
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Tests (py${{ matrix.python }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - "3.11"
          - "3.12"
          - "3.13"
          # - "3.14"
      fail-fast: false
      max-parallel: 3

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-cache-${{ matrix.python }}-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            pip-cache-${{ matrix.python }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"

      - name: Lint (ruff)
        run: |
          python -m pip install ruff==0.4.8
          ruff check . --fix

      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run --concurrency=thread --parallel-mode -m pytest -q
          coverage combine
          coverage xml -i
        env:
          PYTHONWARNINGS: default

      - name: Upload coverage to Coveralls
        if: ${{ secrets.GITHUB_TOKEN != '' }}
        uses: coverallsapp/github-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
